# -*- coding: utf-8 -*-
"""Cancion_a_texto_voz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FQPSZkmco8d3KeDq95Wy34hSURB_LLtm
"""

!pip install git+https://github.com/openai/whisper.git
!sudo apt update && sudo apt install ffmpeg

import whisper

model = whisper.load_model("large")
result = model.transcribe("/content/Cancion/Remember me.mp3")
print(result["text"])
lyrics = result["text"]

!pip install googletrans==4.0.0-rc1

lyrics = result["text"]

# Escribir la letra en un archivo de texto
with open("letra_cancion.txt", "w") as file:
    file.write(lyrics)

print("La letra de la canción ha sido guardada en el archivo 'letra_cancion.txt'")

with open("letra_cancion.txt", "r") as file:
    english_lyrics = file.read()

from googletrans import Translator

translator = Translator()
spanish_lyrics = translator.translate(english_lyrics, src="en", dest="es").text



with open("traduccion_lyrics.txt", "w") as file:
    file.write(spanish_lyrics)

print("La letra de la canción ha sido traducida al español y guardada en el archivo 'traduccion_lyrics.txt'")

"""LECTURA DEL TXT CON VOZ"""

!pip install gTTS

#from gtts import gTTS
#import os

#text = spanish_lyrics
#languaje='es-es'
#speech=gTTS(text=text, lang=languaje, slow = False)
#speech.save("audio.mp3")

#os.system("start audio.mp3")

!pip install pydub

from gtts import gTTS
from pydub import AudioSegment
from pydub.playback import play

text = spanish_lyrics
language = 'es-es'
speed = 1.2

# Genera el audio con gTTS
speech = gTTS(text=text, lang=language, slow=False)
speech.save("audio.mp3")

# Carga el archivo de audio y ajusta la velocidad
audio = AudioSegment.from_mp3("audio.mp3")
audio = audio.speedup(playback_speed=speed)

# Guarda el archivo con la nueva velocidad
audio.export("audio_humano.mp3", format="mp3")